### ISSUE TITLE
Doc: Use Case pxe server

### ISSUE THREAD

**Issue by dschier-wtd** [while-true-do/ansible-role-srv_dhcp#2]
Documenting the pxe setup would be a nice addition. Basically srv_dhcp with some params + srv_tftp.

See also: https://github.com/while-true-do/ansible-role-srv_tftp/issues/2

One can fix a minor typo, too:

```
          pools:
            - name: "my ntwork 2 pool"
              range: "192.168.10.10 192.168.10.20"
```

**Comment by daniel-schier** [comment]
was closed due to wrong commit comment.
